cvg/urls.py
from django.urls import path
from . import views
# from cvg.views import Edit_ad

app_name = 'cvg'

urlpatterns = [
    path('', views.cv_list, name='cv_list'),
    path('cv/<int:pk>/', views.cv_detail, name='cv_detail'),
    path('cv/<int:pk>/preview/', views.cv_preview, name='cv_preview'),
    
    # path('cv/<int:pk>/edit/', Cv_new.as_view(), name='cv_new'),
    path('cv/new/', views.cv_new, name='cv_new'),
    
    # path('cv/<int:pk>/edit/', Cv_edit.as_view(), name='cv_edit'),
    path('cv/<int:pk>/edit/', views.cv_edit, name='cv_edit'),
    
    path('cv/ad/<int:pk>/add', views.add_ad_to_cv, name='add_ad'),
    path('cv/ad/<int:pk>/remove/', views.remove_ad, name='remove_ad'),
    path('cv/ad/<int:pk>/unapprove/', views.unapprove_ad, name='unapprove_ad'),
    path('cv/ad/<int:pk>/edit/', views.edit_ad, name='edit_ad'),
    # path('cv/comment/<int:pk>/edit/', Edit_ad.as_view(), name='edit_ad'),

    path('cv/sd/<int:pk>/add', views.add_sd_to_cv, name='add_sd'),
    path('cv/sd/<int:pk>/remove/', views.remove_sd, name='remove_sd'),
    path('cv/sd/<int:pk>/unapprove/', views.unapprove_sd, name='unapprove_sd'),
    path('cv/sd/<int:pk>/edit/', views.edit_sd, name='edit_sd'),

    path('cv/ed/<int:pk>/add', views.add_ed_to_cv, name='add_ed'),
    path('cv/ed/<int:pk>/remove/', views.remove_ed, name='remove_ed'),
    path('cv/ed/<int:pk>/unapprove/', views.unapprove_ed, name='unapprove_ed'),
    path('cv/ed/<int:pk>/edit/', views.edit_ed, name='edit_ed'),

    path('cv/ind/<int:pk>/add', views.add_ind_to_cv, name='add_ind'),
    path('cv/ind/<int:pk>/remove/', views.remove_ind, name='remove_ind'),
    path('cv/ind/<int:pk>/unapprove/', views.unapprove_ind, name='unapprove_ind'),
    path('cv/ind/<int:pk>/edit/', views.edit_ind, name='edit_ind'),

    path('cv/pd/<int:pk>/add', views.add_pd_to_cv, name='add_pd'),
    path('cv/pd/<int:pk>/remove/', views.remove_pd, name='remove_pd'),
    path('cv/pd/<int:pk>/unapprove/', views.unapprove_pd, name='unapprove_pd'),
    path('cv/pd/<int:pk>/edit/', views.edit_pd, name='edit_pd'),

    path('cv/rd/<int:pk>/add', views.add_rd_to_cv, name='add_rd'),
    path('cv/rd/<int:pk>/remove/', views.remove_rd, name='remove_rd'),
    path('cv/rd/<int:pk>/unapprove/', views.unapprove_rd, name='unapprove_rd'),
    path('cv/rd/<int:pk>/edit/', views.edit_rd, name='edit_rd'),

    path('cv/<int:pk>/delete/', views.delete_cv, name='delete_cv'),
    path('draft/', views.cv_draft_list, name='cv_draft_list'),
    path('cv/<int:pk>/publish/', views.cv_publish, name='cv_publish'),
    path('cv/<int:pk>/comment/', views.add_comment_to_cv, name='add_comment'),
    path('comment/<int:pk>/remove/', views.remove_comment, name='remove_comment'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='approve_comment'),

]

mycvg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from cvg import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('cvg.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(next_page='cvg:cv_list'), name='logout'),
    
    path('signup/', views.signup, name='signup'),
]

cvg/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Academics, Cv, Comment, Skills, Projects, Internships, Extracurricular, Roles

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit  # , Layout, Field


# from crispy_forms.bootstrap import (
#     PrependedText, PrependedAppendedText, FormActions
# )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Sign up', 'Sign up', css_class='btn btn-primary'))

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class Cvform(forms.ModelForm):
    class Meta:
        model = Cv
        exclude = ('published_date', 'created_by', 'edited_by', 'sap_id', 'modified_date')
        # widgets = {
        #     'first_name': forms.TextInput(attrs={'class': 'forms-control input-group-text', }),
        # }


class Academicsform(forms.ModelForm):
    class Meta:
        model = Academics
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Skillsform(forms.ModelForm):
    class Meta:
        model = Skills
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Extracurricularform(forms.ModelForm):
    class Meta:
        model = Extracurricular
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Internshipsform(forms.ModelForm):
    class Meta:
        model = Internships
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Projectsform(forms.ModelForm):
    class Meta:
        model = Projects
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Rolesform(forms.ModelForm):
    class Meta:
        model = Roles
        exclude = ('cv', 'approved', 'edited_by', 'modified_date')


class Commentform(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)




cvg/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Academics, Cv, Comment, Skills, Extracurricular, Internships, Projects, Roles
from .forms import Cvform, Commentform, UserForm, Academicsform, Skillsform, Extracurricularform, Internshipsform, \
    Projectsform, Rolesform
from .custom import *

import os
import subprocess
from subprocess import call
from django.http import FileResponse
from tempfile import mkdtemp, mkstemp
from django.template.loader import render_to_string


# Create your views here.

# unused functions from last app
@login_required
def cv_draft_list(request):
    cvs = Cv.objects.filter(published_date__isnull=True).order_by('-created_date')
    context = {'cvs': cvs}
    return render(request, 'cvg/cv_draft_list.html', context)


@login_required
def cv_publish(request, pk):
    cv = get_object_or_404(Cv, pk=pk)
    cv.published()
    return redirect('cvg:cv_detail', pk=pk)


# comment section
@login_required
def add_comment_to_cv(request, pk):
    cv = get_object_or_404(Cv, pk=pk)
    if request.method == 'POST':
        form = Commentform(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.cv = cv
            comment.save()
            return redirect('cvg:cv_detail', pk=cv.pk)
    else:
        form = Commentform()
        return render(request, 'cvg/addcomment.html', {'form': form})


@login_required
def remove_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('cvg:cv_detail', pk=comment.cv.pk)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('cvg:cv_detail', pk=comment.cv.pk)


# actual start of useful stuff
# csddct = dctc(dct)
def dctc(dct):
    """dictionary cleaner removes null/blank values"""
    null = ""
    cdct = {k: v for k, v in dct.items() if v != null}
    # print(cdct)
    return cdct


# sefunc('mst', csddct)
def sefunc(textemplate, rdct):  # use only for skills and extracurricular
    """
    takes string template and raw dictionary and renders after substitution only
    """
    dct = dctc(rdct)
    with open(f'cvg/static/cvg/{textemplate}.tex', 'r') as template:

        # print(len(dct.keys()))
        d = template.read()  # .replace('first_name','Kshitij') #.split()
        print('Template loaded:')  # Print template for visual cue.

    key_list = list(dct.keys())
    val_list = list(dct.values())

    com = [sub.replace(sub, '%' + sub) for sub in key_list]
    com_dct = {com[i]: " " for i in range(len(com))}

    for key, value in com_dct.items():
        d = d.replace(key, str(value))  # Replace comments key character with null/space

    # print(com_dct)

    res = [sub.replace(sub, 'kk' + sub) for sub in key_list]
    res_dct = {res[i]: val_list[i] for i in range(len(res))}

    # bkp manual method
    for key, value in res_dct.items():
        d = d.replace(key, str(value))  # Replace key character with value character in string

    # print(d)
    return d


# iprf('r_prot', dct)
def iprfunc(textemplate, dct, hstr):  # use only for internships,projects,roles
    """
    takes string template and dictionary object for rendering after substitution only
    """

    with open(f'cvg/static/cvg/{textemplate}.tex', 'r') as template:

        # print(len(dct.keys()))
        d = template.read()  # .replace('first_name','Kshitij') #.split()
        print('Template loaded:')  # Print template for visual cue.

    # for i in pd:
    #     dct=i

    key_list = list(dct.keys())
    val_list = list(dct.values())
    prefix = "\kkkresumeItem{"

    temp_desc = (dct['description']).split('\n')
    # print(len(temp_desc))
    mod_desc = ''
    for aline in temp_desc:
        # print(aline)
        mod_desc = mod_desc + prefix + aline + '}\t'

    d = d.replace('description', mod_desc)
    d = d.replace('kkk', "")
    res = [sub.replace(sub, 'kk' + sub) for sub in key_list]
    res_dct = {res[i]: val_list[i] for i in range(len(res))}
    # res_dct['kdescription'] = mod_desc
    # print(mod_desc)

    # bkp manual method
    for key, value in res_dct.items():
        d = d.replace(key, str(value))  # Replace key character with value character in string
    hstr = hstr + d
    # print(d)
    return hstr


# preview cv
def cv_preview(request, pk):
    cv = get_object_or_404(Cv, pk=pk)
    dcv_id = cv.id
    # null=""

    internships_c = 0
    projects_c = 0
    roles_c = 0

    ad = get_object_or_404(Academics, cv_id=dcv_id)

    cvd = cv.__dict__
    ad_d = ad.__dict__

    cdict = {**cvd, **ad_d}
    # cvs = Cv.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    final = sefunc('base', cdict)

    sd = Skills.objects.filter(cv_id=dcv_id)
    ed = Extracurricular.objects.filter(cv_id=dcv_id)
    
    # sd = get_object_or_404(Skills, cv_id=dcv_id)
    # ed = get_object_or_404(Extracurricular, cv_id=dcv_id) 

    # skill string maker
    if bool(sd):
        sd_d = sd.__dict__
        sd_str = sefunc('pst', sd_d)
        final = final + "\n" + sd_str

    # extracurricular string maker
    if bool(ed):
        ed_d = ed.__dict__
        ed_str = sefunc('mst', ed_d)
        final = final + "\n" + ed_str

    # internship string maker
    ind = Internships.objects.filter(cv_id=dcv_id).order_by('end_year' and 'end_month')
    if bool(ind):
        ind_str = "\section{Internships}"
        for i in ind:
            internships_c += 1
            tidct = i.__dict__
            ind_str = iprfunc('r_irt', tidct, ind_str)
        final = final + "\n" + ind_str

    # projects string maker
    pd = Projects.objects.filter(cv_id=dcv_id).order_by('end_year' and 'end_month')
    if bool(pd):
        pd_str = "\section{Projects}"
        for j in pd:
            projects_c += 1
            tjdct = j.__dict__
            pd_str = iprfunc('r_prot', tjdct, pd_str)
        final = final + "\n" + pd_str

    rd = Roles.objects.filter(cv_id=dcv_id).order_by('end_year' and 'end_month')
    if bool(rd):
        rd_str = "\section{Roles}"
        for k in rd:
            roles_c += 1
            tkdct = k.__dict__
            rd_str = iprfunc('r_irt', tkdct, rd_str)
        final = final + "\n" + rd_str

    suffix="\end{document}"
    final = final + suffix
    #
    #
    #
    # make_pdf()
    filename = str(cv.sap_id)
    
    cwd = os.getcwd()  # current working directory
    stdir = os.path.join(cwd, "cvg\static\cvg\custom")  # "test.tex") # static directory
    fp = os.path.join(cwd, "cvg\static\cvg\custom", f"{filename}.pdf")
    os.chdir(stdir)

    # try:
    #     os.remove(f"{filename}.pdf")
    # except:
    #     pass
    # finally:
    #     print("reached here")

    f = open(f"{filename}.tex", "w")
    f.write(final)
    f.close()

    try:
       subprocess.check_call(['pdflatex', '-interaction=nonstopmode', f'{filename}.tex']) 

    except :
        # optional block
        # Handling of exception (if required)
        pass

    else:
        # execute if no exception
        pass

    finally:
        # Some code .....(always executed)
        pass
    
    os.remove(f"{filename}.aux")
    os.remove(f"{filename}.log")
    os.remove(f"{filename}.out")
    os.chdir(cwd)

    return FileResponse(open(fp, 'rb'), content_type='application/pdf')

#


# signup custom view
def signup(request):
    if request.user.is_authenticated:
        return redirect('cvg:cv_list')
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('cvg:cv_list')
    else:
        form = UserForm()
    return render(request, 'cvg/signup.html', {'form': form})


# Home
@login_required
def cv_list(request):
    cvs = Cv.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context = {'cvs': cvs}
    return render(request, 'cvg/cv_list.html', context)


# s1-step1 takes to details of cv
@login_required
def cv_detail(request, pk):
    cv = get_object_or_404(Cv, pk=pk)
    context = {'cv': cv}
    return render(request, 'cvg/cv_detail.html', context)


# views related to cv-basic details
@login_required
def cv_new(request):
    if request.method == 'POST':
        form = Cvform(request.POST)
        if form.is_valid():
            try:
                cvd = form.save(commit=False)
                cvd.sap_id = int(str(request.user))
                cvd.created_by = request.user
                cvd.published_date = timezone.now()
                cvd.modified_date = timezone.now()
                cvd.edited_by = request.user
                cvd.save()
                return redirect('cvg:cv_detail', pk=cvd.pk)
            except:
                return HttpResponse("Please maintain only one CV atleast for now, might be included in future update")
                # TODO: make this later          
    else:
        form = Cvform()
    return render(request, 'cvg/form.html', {'form': form})


## generic form of above view
# class Cv_new(LoginRequiredMixin, CreateView):
#     # fields = '__all__'
#     model = Cv

cvg/templates/cvg/ad.html
{% extends 'cvg/base.html' %} {% block title %} Adding details! {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container pads">
    <h2>Academics Details</h2>
    <form class="cv-form-blog" method="POST">
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">submit details</button>
    </form>
</div>

{% endblock %}

cvg/templates/cvg/add_ad.html
{% extends 'cvg/base.html' %} {% block title %} Adding details! {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container pads">
    <h2>Academics Details</h2>
    <form class="cv-form-blog" method="POST">
        {% csrf_token %} 
        {{ adform|crispy }}
        <button type="submit" class="btn btn-primary">submit details</button>
    </form>
</div>

{% endblock %}

cvg/templates/cvg/addcomment.html
{% extends 'cvg/base.html' %} {% block title %} Adding comment! {% endblock %}
{% block content %}
<div class="comment">
    <h2>New Comment</h2>
    <form class="cv-form-blog" method="POST">
        {% csrf_token %} {{ adform.as_p }}
        <button type="submit" class="btn btn-primary">Cv Comment</button>
    </form>
</div>
{% endblock %}

cvg/templates/cvg/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata&display=swap" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="{% static 'cvg/style.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

    <div class="page-header">
        {% if user.is_authenticated %}
        <!-- <a href="{% url 'cvg:cv_draft_list' %}" class="top-menu"><i class="fa fa-envelope fa-2x"></i></a> -->
        <a href="{% url 'cvg:cv_new' %}" class="top-menu"><i class="fa fa-plus fa-2x"></i></a>
        <p class="top-menu">Hello, {{user.username}} <small>(<a href="{% url 'logout' %}">logout</a></small>)</p>
        {% else %}
        <a href="{% url 'login' %}" class="top-menu"><i class="fa fa-sign-in fa-2x" aria-hidden="true"></i></a>
        {% endif %}

        <h1><a href="{% url 'cvg:cv_list' %}">CVgenrator</a></h1>
    </div>
    <br>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <br>

    <div class="page-header">
    <br>
    </div>
</body>

</html>

cvg/templates/cvg/cv_draft_list.html
{% extends 'cvg/base.html' %}
{% block content %}

{% for cv in cvs %}
    <div class="cv">
        <!-- <p>{{cv}}</p> -->
        <p class="date">created: {{cv.created_date|date:'d-m-Y'}}</p>
        <h2><a href="{% url 'cvg:cv_detail' pk=cv.pk %}">{{cv.title}}</a></h2>
        <p>{{cv.text|truncatechars:200}}</p>

    </div>
    
{% endfor %}

{% endblock %}

cvg/templates/cvg/cv_list.html
{% extends 'cvg/base.html' %}

{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-8">
        {% for cv in cvs %}
        <div>
            {% if user.is_authenticated and request.user == cv.created_by or user.is_superuser %}
            <!-- <div class='date'>  <p>Published: {{cv.published_date}}</p> </div> -->
            <h2><a href="{% url 'cvg:cv_detail' pk=cv.pk %}">{{cv.sap_id}}</a></h2>
            <p>{{cv.text }}</p>
            {% endif %}
        </div>
        </div>
        <br>
        {% endfor %}
    </div>
</div>

</body>
</html>
{% endblock %}

cvg/templates/cvg/form.html
{% extends 'cvg/base.html' %} {% block title %} Adding details! {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container pads">
    <h2>Please fill details accordingly</h2>
    <form class="cv-form-blog" method="POST">
        {% csrf_token %} 
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary">submit details</button>
    </form>
</div>
    <br>
    <br>
    <br>

{% endblock %}

cvg/templates/cvg/signup.html
{% extends 'cvg/base.html' %}

{% block title %}Signup{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h6 style="text-align:center; font-family: sans-serif"> Please enter relevant details to make an account </h6>

<div class="panel panel-default" style="width: 400px; margin:0 auto">
{#    <div class="panel-body">#}
{#        {% crispy form %}#}
{#    </div>#}

    <form method="POST" action="{% url 'signup' %}">
    {% csrf_token %}
    <table>
      <tr>
        <td>SAP ID </td>
        <!-- {{ form.username.label_tag }} -->
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
      <tr>
        <td>{{ form.email.label_tag }}</td>
        <td>{{ form.email }}</td>
      </tr>
    </table>
        <br>
    <!-- <input type="submit" value="Login"  /> -->
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn btn-primary">Signup</button>
  </form>

    <br>
</div>

{% endblock %}